name: Build wheel

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  upload_pypi:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/moirae
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build sdist
        run: pipx run build --sdist

      - uses: pypa/gh-action-pypi-publish@release/v1
        #with:
          # To test: repository-url: https://test.pypi.org/legacy/
